name: Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Ubuntu Linux
    runs-on: ubuntu-24.04
    steps:
      - name: Set up machine
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgdal-dev
      - name: Set up rust compiler
        run: rustup update stable && rustup default stable
      - name: Check out project sources
        uses: actions/checkout@v4
      - run: cargo build --verbose
      - run: cargo test --verbose
